repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --ignore=W503]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    - id: mypy
      stages:
        - pre-commit
      additional_dependencies:
        - "chainlit==1.1.402"
        - "openai==1.47.1"
        - "pydantic==2.9.2"
        - "pydantic-settings==2.8.1"
      args: ["--config-file", "/workspace/pyproject.toml"]
